server.port: 8081

spring.rabbitmq:
  host: 127.0.0.1
  port: 5672
  username: guest
  password: guest

spring.cloud.stream:
  defaultBinder: rabbit
  default.contentType: application/json
  bindings:
    message-out-0:
      destination: messages

---
spring.config.activate.on-profile: docker
spring.rabbitmq.host: lavinmq

---
spring.config.activate.on-profile: auditgroup
spring.cloud.stream:
  bindings:
    message-out-0:
      producer:
        required-groups: auditGroup

---
spring.config.activate.on-profile: partitioned

spring.cloud.stream.bindings.message-out-0.producer:
  partition-key-expression: headers['partitionKey']
  partition-count: 2